-- Migration: Add missing Polymarket fields to event_groups and markets
-- Run this in Supabase SQL Editor

-- Event-level fields
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS comment_count INTEGER DEFAULT 0;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS competitive NUMERIC DEFAULT 0;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS volume_1wk NUMERIC DEFAULT 0;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS volume_1mo NUMERIC DEFAULT 0;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS open_interest NUMERIC DEFAULT 0;
ALTER TABLE event_groups ADD COLUMN IF NOT EXISTS start_date TEXT;

-- Market-level fields
ALTER TABLE markets ADD COLUMN IF NOT EXISTS best_bid NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS best_ask NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS spread NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS last_trade_price NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS price_change_1h NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS price_change_24h NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS price_change_1w NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS price_change_1m NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS competitive NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS volume_1wk NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS volume_1mo NUMERIC DEFAULT 0;
ALTER TABLE markets ADD COLUMN IF NOT EXISTS submitted_by TEXT;
